const categories = [
  {
    id: 134,
    foods_displayed_in_menu: [
      {
        id: 786,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Samosa With Chutny (Per/Pc.)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "1.75",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Delicious Savory Pastries with Potato Filling served with a tangy sauce ",
        published_date: "2023-08-13T17:58:05.338355Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 787,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Vegetable Samosa  Chaat",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Savory Pastries with Potato Filling Serve with Chick Pea & yogurt Curry (2 per order) ",
        published_date: "2023-08-07T02:32:22.160258Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 788,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Aloo Tikki Chaat",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Potato patty filled with paneer, lentils, peas and deep fried. Vegetable Pakora",
        published_date: "2023-08-07T02:32:51.975572Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 789,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Vegetable Pakora",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Deep fried fritters of garden-fresh vegetables.",
        published_date: "2023-08-07T02:33:20.021717Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 790,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Delhi Chaat",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "7.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Crispy Bites & Lentil ball mixed with potato. chickpea, Yogurt & Sweet chutney ",
        published_date: "2021-10-24T22:39:29.785992Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 791,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Veg Kabab (2Pc)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "8.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Mashed vegetables roast in tandoor. Serve with cucumber salad and special home-made sauce ",
        published_date: "2021-10-24T22:40:59.600833Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 792,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Stuffed Paneer Pakora",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "12.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Homemade Cheese Stuffed with Tomatoes & Spices then dipped in special spicy batter and deep fries. ",
        published_date: "2023-08-07T02:37:52.580079Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 793,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "5 Pc Pav Bhaji\t",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "12.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Pav bhaji consists of bhaji (a thick potato-based curry) garnished with Coriander, chopped Onion and a dash of lemon and baked pav. (small loaf of bread) ",
        published_date: "2023-08-07T02:38:31.522872Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 794,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Chole Bhature",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "12.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Deep Fried white leavened bread served with chick pea curry and salad.",
        published_date: "2023-08-07T02:38:59.100407Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 795,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Amritsari Kulcha (Potato & Paneer Naan)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Leavened bread stuffed with potatoes. onion & herbs served with chick pea curry &salad ",
        published_date: "2023-08-07T02:39:27.138867Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 796,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Veg. Manchurian",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Deep fried vegetable balls cooked with our special tangy sauce",
        published_date: "2023-08-07T02:40:13.673131Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 797,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Hakka Noodles",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Veg. noodles loaded with veggies and herbs with special\r\nSoy sauce and spices\r\n",
        published_date: "2023-08-07T02:40:33.978950Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 798,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Veg Fried Rice",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Basmati rice, loaded with veggies and herbs with special Soy sauce and spices. ",
        published_date: "2023-08-07T02:40:53.742107Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 799,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "Paneer Tikka",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Cottage Cheese marinated with tandoori spices roasted in tandoor and Serve with cucumber salad and  special home-made sauce",
        published_date: "2023-08-07T02:41:21.169390Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
      {
        id: 800,
        category_names: ["STARTERS"],
        combo_choices: [],
        title: "No Meat Chicken Tikka ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Mashed Soya chunks cooked in clay oven marinated with  tandoori spices and coated with cream, cashew nuts which gives a heavenly flavour Serve with cucumber salad and special home-made sauce",
        published_date: "2023-08-07T02:43:12.310612Z",
        delete_status: 0,
        menu_category: 134,
        owner: 17,
        tagged_categories: [134],
      },
    ],
    title: "STARTERS",
    priority: 1,
    image: null,
    published_date: "2021-10-23T18:22:33.721201Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 135,
    foods_displayed_in_menu: [
      {
        id: 801,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "No Meat Chicken Curry (Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious curry chicken without the chicken\n(using soya protein)\n",
        published_date: "2021-10-26T23:15:13.886189Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 802,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "No Meat Chicken Korma(Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious chicken Korma without the chicken (using soya protein) Cooked with nuts, and creamy Indian gravy.",
        published_date: "2021-10-27T02:22:58.471745Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 803,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "No Meat Kadhai Chicken(Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious chicken karahi without the chicken (using soya protein) With green/red paper, onion with healthy herbs.",
        published_date: "2021-10-27T02:42:58.751354Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 804,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "No Meat Butter Chicken (Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of a Butter Chicken without the chicken\r\n(using soy protein). A special in house mock meat preparation\r\n",
        published_date: "2023-08-07T02:48:45.672906Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 805,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "No Meat Chicken Tikka Masala (Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "17.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of a Chicken Tikka Masala without chicken (using soy protein). A special in house mock meat preparation with onion, tomato, ginger, garlic, cashew nuts and our home-made spices ",
        published_date: "2023-08-07T02:52:19.978398Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 806,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Dal Fry Yellow",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Indian lentil recipe made with yellow dal, onions, tomatoes and spices",
        published_date: "2023-08-07T02:53:03.783058Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 807,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Chana Masala",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Chickpeas cooked in a variety of Indian spices in a curry sauce",
        published_date: "2023-08-07T02:53:49.217634Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 808,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Mix Veg.",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "A dish made with mixed vegetable and Indian spices",
        published_date: "2023-08-07T02:54:28.966855Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 809,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Dal Makhani (Punjabi Style)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Whole black lentil, red kidney beans cooked in butter and cream.",
        published_date: "2023-08-07T02:55:00.768516Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 810,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Okra Masala",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Stirfried okra cooked with spice mix such as garam masala and other combination of other ground spices.",
        published_date: "2023-08-07T02:55:30.642349Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 811,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Aloo Gobi",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A vegetarian dish made with potatoes, cauliflower, and Indian spices",
        published_date: "2023-08-07T02:55:55.690511Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 812,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Baingan Bhartha (Egg Plant)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Baked and mashed eggplant cooked with onion, tomato, ginger and Indian spices and butter",
        published_date: "2023-08-07T02:56:54.149632Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 813,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Shahi Paneer",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Cottage cheese cooked in rich creamy curry sauce and cashew nuts ",
        published_date: "2023-08-07T02:57:28.320068Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 814,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Vegetable Korma",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A colourful combination of fresh vegetables cooked in onion, tomatoes and cashew nut base sauce Vegetable ",
        published_date: "2023-08-07T02:58:01.903790Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 815,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Goa Curry",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Vegetable cooked with a unique blend of coconut cream  & fresh cilantro",
        published_date: "2023-08-07T03:00:28.185260Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 816,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Paneer Butter Masala (Paneer Punjabi)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "17.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A rich curry prepared with cottage cheese, butter, cashew nuts and succulent Indian spices ",
        published_date: "2023-08-07T03:00:50.586004Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 817,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Palak Paneer",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A rich spinach gravy made with paneer and other Indian spices",
        published_date: "2023-08-07T03:01:29.978038Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 818,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Paneer Methi",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Paneer cooked in our special creamy onion tomato sauce with butter and fenugreek leaves",
        published_date: "2023-08-07T03:01:46.166336Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
      {
        id: 882,
        category_names: ["VEGETARIAN"],
        combo_choices: [],
        title: "Malai Kofta",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Cheese and vegetable balls cooked in rich creamy curry sauce with cashew nuts ",
        published_date: "2023-08-07T03:02:56.013866Z",
        delete_status: 0,
        menu_category: 135,
        owner: 17,
        tagged_categories: [135],
      },
    ],
    title: "VEGETARIAN",
    priority: 3,
    image: null,
    published_date: "2021-10-27T02:46:50.614859Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 136,
    foods_displayed_in_menu: [
      {
        id: 832,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Vegetable Pakora (Fritters)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Delicious mixed vegetable fritters served with a tangy sauce",
        published_date: "2023-08-07T03:04:13.289324Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 833,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Samosa Chaat",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Savory Pastries with Potato Filling Serve with Chick Pea Curry (2 per order)",
        published_date: "2023-08-07T03:04:48.594603Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 834,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Chana Masala",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:05:14.795174Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 835,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Vegetable Korma",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Assorted vegetables in a special vegan creamy korma gravy with nuts.",
        published_date: "2023-08-07T03:09:45.207993Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 836,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Baingan Bharta (Egg Plant)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Baked and mashed eggplant cooked with onion, tomato, ginger and Indian spices",
        published_date: "2023-08-07T03:10:41.113959Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 837,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan No Meat Chicken Khorma",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious chicken Khorma without the chicken (using soya protein)",
        published_date: "2021-10-25T06:29:38.628728Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 838,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan No Meat Kadhai Chicken",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious chicken karahi without the chicken (using soya protein)",
        published_date: "2021-10-25T06:30:02.851025Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 839,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Paneer Methi",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious Paneer methi without the Paneer (using tofu soya protein)",
        published_date: "2021-10-25T06:30:26.625677Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 840,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan No Meat Tikka Masala",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious chicken tikka masala without the chicken (Chef Special) (using soya protein)",
        published_date: "2023-08-07T03:15:21.673268Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 841,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan No Meat Butter Chicken",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious butter chicken without the chicken (using soya protein)",
        published_date: "2023-08-07T03:15:47.337176Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 842,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan No Meat Chicken Curry",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of delicious curry chicken without the chicken (using soya protein)",
        published_date: "2021-10-25T06:36:37.338642Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 843,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Palak Chana",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Spinach puree cooked in ginger, tomato, chick pea and healthy spices",
        published_date: "2023-08-07T03:16:52.373531Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 844,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Aloo Gobi",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A vegetarian dish made with potatoes, cauliflower, and Indian spices",
        published_date: "2023-08-07T03:28:57.651343Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 845,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Vegetable Goa Curry",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "16.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "A dish made with mixed vegetables, coconut cream and Indian spices Vegan Okra Masala",
        published_date: "2023-08-07T03:30:30.572797Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 846,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Okra Masala",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Stir fried okra cooked with spice mix such as garam masala and other combination of other ground spices.",
        published_date: "2023-08-07T03:31:17.961188Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 847,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Black Dal Fry ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Indian lentil recipe made with black lentils, onions, tomatoes, and spices.",
        published_date: "2023-08-07T03:31:51.268074Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 848,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Yellow Dal Fry ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "13.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Indian lentil recipe made with yellow lentils, onions, tomatoes, and spices.",
        published_date: "2023-08-07T03:32:14.328944Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 849,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Vegetable Korma ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Assorted vegetables in a special vegan creamy korma gravy with nuts.",
        published_date: "2023-08-07T03:32:40.388825Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 850,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Baingan Bharta (Eggplant) ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Baked and mashed eggplant cooked with onion, tomato, ginger, and Indian spices",
        published_date: "2023-08-07T03:33:04.175224Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
      {
        id: 853,
        category_names: ["VEGAN"],
        combo_choices: [],
        title: "Vegan Tawa Roti ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "2.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:35:28.209759Z",
        delete_status: 0,
        menu_category: 136,
        owner: 17,
        tagged_categories: [136],
      },
    ],
    title: "VEGAN",
    priority: 4,
    image: null,
    published_date: "2021-10-27T02:46:59.577975Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 137,
    foods_displayed_in_menu: [
      {
        id: 851,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Tandoori Naan ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "2.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "A must for every meal!! White leavened bread.",
        published_date: "2023-08-07T03:34:36.214466Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 852,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Vegan Roti ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "1.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Unleavened whole wheat bread.",
        published_date: "2023-08-07T03:36:47.775437Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 854,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Butter Naan ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "White leaved bread with butter",
        published_date: "2023-08-07T03:37:11.881798Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 855,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Garlic Naan ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Perfectly baked in tandoor with garlic.",
        published_date: "2023-08-07T03:37:43.228771Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 856,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Vegan Plain Paratha",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Multi-layered flaky whole wheat bread baked in tandoor.",
        published_date: "2021-10-25T06:39:07.845167Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 857,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Onion Garlic Naan  ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "6.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "White leaved bread baked with onion.",
        published_date: "2023-08-07T03:38:20.161485Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 858,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Onion Garlic Paratha ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "6.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "White leaved bread baked with onion.",
        published_date: "2023-08-07T03:39:22.630463Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
      {
        id: 859,
        category_names: ["TANDOORI BREAD"],
        combo_choices: [],
        title: "Paneer Kulcha",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Paneer kulcha is flatbread and very famous in North Indian for its crispy layers of dough and delicious variety of fillings.",
        published_date: "2023-08-07T03:38:41.744967Z",
        delete_status: 0,
        menu_category: 137,
        owner: 17,
        tagged_categories: [137],
      },
    ],
    title: "TANDOORI BREAD",
    priority: 5,
    image: null,
    published_date: "2021-10-27T02:47:06.404421Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 138,
    foods_displayed_in_menu: [
      {
        id: 860,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Steam Plain Rice",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:39:51.070168Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 861,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Jeera Rice",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "4.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Rice cooked with cumin seeds.",
        published_date: "2023-08-07T03:40:05.616260Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 862,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Veg Pulao (Green Peas Pulao)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Basmati rice cooked with vegetables",
        published_date: "2023-08-07T03:40:34.651049Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 863,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Coconut Rice",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Basmati rice cooked with coconut.",
        published_date: "2023-08-07T03:40:56.512268Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 864,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Kesar Pulao (Saffron Rice)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "9.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Rice cooked with saffron and nuts.",
        published_date: "2023-08-07T03:41:12.179496Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 865,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Vegetable Biryani",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "14.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Basmati rice cooked with fresh vegetables and Indian spices.",
        published_date: "2023-08-07T03:41:45.652303Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 866,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "Paneer Biryani",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Basmati rice cooked with vegetables and cottage cheese.",
        published_date: "2023-08-07T03:41:59.242051Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
      {
        id: 867,
        category_names: ["RICE & BIRYANI"],
        combo_choices: [],
        title: "No Meat Chicken Biryani (Beyond Meat)",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "15.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "All the goodness of a chicken biryani without chicken (using soy protein). A special in-house mock meat preparation.",
        published_date: "2023-08-07T03:42:20.144898Z",
        delete_status: 0,
        menu_category: 138,
        owner: 17,
        tagged_categories: [138],
      },
    ],
    title: "RICE & BIRYANI",
    priority: 6,
    image: null,
    published_date: "2021-10-27T02:47:11.022855Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 139,
    foods_displayed_in_menu: [
      {
        id: 868,
        category_names: ["CONDIMENTS"],
        combo_choices: [],
        title: "Mixed Pickle (Achaar) ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "2.25",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:43:08.741469Z",
        delete_status: 0,
        menu_category: 139,
        owner: 17,
        tagged_categories: [139],
      },
      {
        id: 869,
        category_names: ["CONDIMENTS"],
        combo_choices: [],
        title: "Mango Chutney ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.25",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:43:34.313349Z",
        delete_status: 0,
        menu_category: 139,
        owner: 17,
        tagged_categories: [139],
      },
      {
        id: 870,
        category_names: ["CONDIMENTS"],
        combo_choices: [],
        title: "Mint Chutney Spicy ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.25",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:43:59.937928Z",
        delete_status: 0,
        menu_category: 139,
        owner: 17,
        tagged_categories: [139],
      },
      {
        id: 871,
        category_names: ["CONDIMENTS"],
        combo_choices: [],
        title: "Raita",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "5.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Refreshing homemade yogurt with fresh vegetables.",
        published_date: "2023-08-07T03:44:15.016380Z",
        delete_status: 0,
        menu_category: 139,
        owner: 17,
        tagged_categories: [139],
      },
      {
        id: 872,
        category_names: ["CONDIMENTS"],
        combo_choices: [],
        title: "Butter Chicken Sauce ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "2.99",
        food_types: null,
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2021-10-25T06:45:37.163803Z",
        delete_status: 0,
        menu_category: 139,
        owner: 17,
        tagged_categories: [139],
      },
    ],
    title: "CONDIMENTS",
    priority: 7,
    image: null,
    published_date: "2021-10-27T02:47:28.861054Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 140,
    foods_displayed_in_menu: [
      {
        id: 877,
        category_names: ["DRINKS"],
        combo_choices: [],
        title: "Pop Cans ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "2.25",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:45:40.999470Z",
        delete_status: 0,
        menu_category: 140,
        owner: 17,
        tagged_categories: [140],
      },
      {
        id: 878,
        category_names: ["DRINKS"],
        combo_choices: [],
        title: "Mango Lassi ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "5.50",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Lassi made from fresh yogurt milk, mango pulp, and sugar.",
        published_date: "2023-08-07T03:46:32.857824Z",
        delete_status: 0,
        menu_category: 140,
        owner: 17,
        tagged_categories: [140],
      },
      {
        id: 879,
        category_names: ["DRINKS"],
        combo_choices: [],
        title: "Plain Lassi ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "3.99",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Lassi made from fresh yogurt milk and sugar or salt.",
        published_date: "2021-11-14T21:07:20.040634Z",
        delete_status: 0,
        menu_category: 140,
        owner: 17,
        tagged_categories: [140],
      },
    ],
    title: "DRINKS",
    priority: 8,
    image: null,
    published_date: "2021-10-27T02:47:44.201584Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 141,
    foods_displayed_in_menu: [
      {
        id: 880,
        category_names: ["DINNER"],
        combo_choices: [],
        title: "Dinner For Two",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "44.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Two Vegetarian dishes of your choice with rice, two naans, two gulab jamun, or rice pudding, and two pieces of samosa or veg pakoras with chutney.",
        published_date: "2023-08-07T03:47:23.040339Z",
        delete_status: 0,
        menu_category: 141,
        owner: 17,
        tagged_categories: [141],
      },
      {
        id: 881,
        category_names: ["DINNER"],
        combo_choices: [],
        title: "Dinner For Four",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "82.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Two large vegetarian dishes of your choice with large rice, four naans, four gulab jamun, or rice pudding for four, and four pieces of samosa or twelve veg pakoras with chutney.",
        published_date: "2023-08-07T03:47:45.599584Z",
        delete_status: 0,
        menu_category: 141,
        owner: 17,
        tagged_categories: [141],
      },
    ],
    title: "DINNER",
    priority: 2,
    image: null,
    published_date: "2021-10-27T02:46:27.834564Z",
    delete_status: 0,
    owner: 17,
  },
  {
    id: 144,
    foods_displayed_in_menu: [
      {
        id: 873,
        category_names: ["DESSERT"],
        combo_choices: [],
        title: "Rice Pudding  ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "5.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "Rice cooked with flavored milk.",
        published_date: "2023-08-07T03:48:22.745226Z",
        delete_status: 0,
        menu_category: 144,
        owner: 17,
        tagged_categories: [144],
      },
      {
        id: 874,
        category_names: ["DESSERT"],
        combo_choices: [],
        title: "Mango Rice Pudding ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "6.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description: "",
        published_date: "2023-08-07T03:48:37.066931Z",
        delete_status: 0,
        menu_category: 144,
        owner: 17,
        tagged_categories: [144],
      },
      {
        id: 875,
        category_names: ["DESSERT"],
        combo_choices: [],
        title: "Gulab Jamun (2 Pcs)  ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "4.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Pastry ball made of dry milk, deep-fried, and dipped in sweet syrup.",
        published_date: "2023-08-07T03:49:05.506447Z",
        delete_status: 0,
        menu_category: 144,
        owner: 17,
        tagged_categories: [144],
      },
      {
        id: 876,
        category_names: ["DESSERT"],
        combo_choices: [],
        title: "Saffron Ras Malai ",
        is_combo: false,
        is_vegan: false,
        is_vegetarian: false,
        is_gluten_free: false,
        upcell_enabled: false,
        image: null,
        enable_image_display: true,
        price: "6.00",
        food_types: "null",
        dish_priority: 0,
        is_takeout_enabled: true,
        is_delivery_enabled: true,
        discount: "0.00",
        description:
          "Flattened balls of cottage cheese soaked in thickened boiled milk with the goodness of saffron.",
        published_date: "2023-08-07T03:49:29.589342Z",
        delete_status: 0,
        menu_category: 144,
        owner: 17,
        tagged_categories: [144],
      },
    ],
    title: "DESSERT",
    priority: 9,
    image: null,
    published_date: "2021-10-27T02:47:48.535062Z",
    delete_status: 0,
    owner: 17,
  },
];
